# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: .circleci/build-update-file
      - store_artifacts:
          path: tmp/build

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: go get github.com/aktau/github-release
      - run: .circleci/release
workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
        requires:
          - build
        filters:
          branches:
            only: feature/circleci
